server:
  port: 8090
  servlet:
    context-path: /com.landkay.homecare
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  application:
    name: homecare
  http:
    encoding:
      charset: UTF-8


mybatis:
  mapper-locations: classpath*:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.landkay.springboot.model
  #config-locations: classpath:mybatis-config.xml

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
    username: landkay
    password: landkay
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


---
spring:
  profiles: prd

  datasource:
    #url : jdbc:mysql://localhost:3306/newbirds
    #username : root
    #password : mymysql
    #driverClassName : com.mysql.jdbc.Driver