spring:
  profiles:
    active: dev
  application:
    name: com.landkay.springboot
  http:
    encoding:
      charset: UTF-8

server:
  port: 8090
  servlet:
    context-path: /com.landkay.springboot
  session-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8


mybatis:
  mapper-location: classpath*:mapper/**/*.xml
  type-aliases-package: com.landkay.springboot.model

---
spring:
  profiles: dev
  datasource:
    url : jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
    username : landkay
    password : landkay
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #driverClassName: com.mysql.jdbc.Driver


---
spring:
  profiles: prd

  datasource:
    #url : jdbc:mysql://localhost:3306/newbirds
    #username : root
    #password : mymysql
    #driverClassName : com.mysql.jdbc.Driver